name: Frontend deploy

on: [push]

defaults:
  run:
    working-directory: web

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Remove .env
        uses: JesseTG/rm@v1.0.3
        with:
          path: .env

      - run: npm install
      - run: npm run deploy
